# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spacex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspacex.proto\x12\x06spacex\".\n\rLaunchRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"2\n\x0eLaunchResponse\x12 \n\x08launches\x18\x01 \x03(\x0b\x32\x0e.spacex.Launch\"E\n\x06Launch\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03 \x01(\t\x12\x10\n\x08\x64\x61te_utc\x18\x04 \x01(\t2O\n\rLaunchService\x12>\n\x0bGetLaunches\x12\x15.spacex.LaunchRequest\x1a\x16.spacex.LaunchResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LAUNCHREQUEST._serialized_start=24
  _LAUNCHREQUEST._serialized_end=70
  _LAUNCHRESPONSE._serialized_start=72
  _LAUNCHRESPONSE._serialized_end=122
  _LAUNCH._serialized_start=124
  _LAUNCH._serialized_end=193
  _LAUNCHSERVICE._serialized_start=195
  _LAUNCHSERVICE._serialized_end=274
# @@protoc_insertion_point(module_scope)
